package quickbi_public

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// UserGroupModelsItem is a nested struct in quickbi_public response
type UserGroupModelsItem struct {
	IdentifiedPath    string `json:"IdentifiedPath" xml:"IdentifiedPath"`
	ParentUsergroupId string `json:"ParentUsergroupId" xml:"ParentUsergroupId"`
	ModifiedTime      string `json:"ModifiedTime" xml:"ModifiedTime"`
	CreateUser        string `json:"CreateUser" xml:"CreateUser"`
	UsergroupName     string `json:"UsergroupName" xml:"UsergroupName"`
	CreateTime        string `json:"CreateTime" xml:"CreateTime"`
	UsergroupDesc     string `json:"UsergroupDesc" xml:"UsergroupDesc"`
	UsergroupId       string `json:"UsergroupId" xml:"UsergroupId"`
	ModifyUser        string `json:"ModifyUser" xml:"ModifyUser"`
}
