package quotas

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// QuotaApplication is a nested struct in quotas response
type QuotaApplication struct {
	Status           string                 `json:"Status" xml:"Status"`
	DesireValue      int                    `json:"DesireValue" xml:"DesireValue"`
	QuotaActionCode  string                 `json:"QuotaActionCode" xml:"QuotaActionCode"`
	QuotaName        string                 `json:"QuotaName" xml:"QuotaName"`
	ApplicationId    string                 `json:"ApplicationId" xml:"ApplicationId"`
	Reason           string                 `json:"Reason" xml:"Reason"`
	AuditReason      string                 `json:"AuditReason" xml:"AuditReason"`
	QuotaDescription string                 `json:"QuotaDescription" xml:"QuotaDescription"`
	ProductCode      string                 `json:"ProductCode" xml:"ProductCode"`
	QuotaArn         string                 `json:"QuotaArn" xml:"QuotaArn"`
	ApplyTime        string                 `json:"ApplyTime" xml:"ApplyTime"`
	ApproveValue     float64                `json:"ApproveValue" xml:"ApproveValue"`
	Dimension        map[string]interface{} `json:"Dimension" xml:"Dimension"`
	NoticeType       int64                  `json:"NoticeType" xml:"NoticeType"`
	EffectiveTime    string                 `json:"EffectiveTime" xml:"EffectiveTime"`
	ExpireTime       string                 `json:"ExpireTime" xml:"ExpireTime"`
	QuotaUnit        string                 `json:"QuotaUnit" xml:"QuotaUnit"`
}
